# This file was generated by GoReleaser. DO NOT EDIT.
cask "obsidian-preference-sync" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "db6fff391a0ed28477a51cdd33a151a2de8ee395696df59c1b910a233eee313d"
      url "https://github.com/tyPhoon-collab/obsidian-preference-sync/releases/download/v#{version}/obsidian-preference-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "785171338a26c797ab3fb1076d5d3a6ea10e5bee57bf6f53f939ad5b69e9dd19"
      url "https://github.com/tyPhoon-collab/obsidian-preference-sync/releases/download/v#{version}/obsidian-preference-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0ed4202ade25d1710aa124102a3a1e476d6af89829a0c774cd336e0ff9f44d71"
      url "https://github.com/tyPhoon-collab/obsidian-preference-sync/releases/download/v#{version}/obsidian-preference-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10c7a60669e4211aef448c8668deab10891fefc2748fdf90d340b5876e0471f5"
      url "https://github.com/tyPhoon-collab/obsidian-preference-sync/releases/download/v#{version}/obsidian-preference-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "obsidian-preference-sync"
  desc "Synchronize selected Obsidian plugins, plugin settings, and app settings"
  homepage "https://github.com/tyPhoon-collab/obsidian-preference-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "obsidian-preference-sync"

  # No zap stanza required

end
